name: global_language_distribution_map
description: "Global Language Distribution Map - Visualize the world's linguistic diversity"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  flutter_map: ^7.0.2
  flutter_map_marker_cluster: ^1.4.0
  latlong2: ^0.9.1
  xml: ^6.5.0
  file_saver: ^0.2.14
  flutter_tts: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/
