import 'package:global_language_distribution_map/data/models/language.dart';
import 'package:xml/xml.dart';

/// Service for generating KML (Keyhole Markup Language) files from language data.
///
/// This is a pure-data service with no Flutter/UI dependencies.
/// The generated KML is compatible with Google Earth and Liquid Galaxy.
///
/// Architecture:
/// - Generates complete KML documents with styles and placemarks
/// - Organizes placemarks into folders by endangerment status
/// - Includes `<LookAt>` elements for each placemark (ready for LG viewpoint sync)
/// - KML string output can be written to file or sent to LG via SSH
///
/// Extension points for Liquid Galaxy:
/// - [generateLookAt] → send independently to LG master for viewpoint sync
/// - Folder structure → toggle folder visibility on LG
/// - Full KML string → write to LG's /var/www/html/kml/ via SSH
class KmlService {
  KmlService._();

  // ─── KML Namespace ──────────────────────────────────────────────────────────

  static const String _kmlNamespace = 'http://www.opengis.net/kml/2.2';

  // ─── Endangerment → KML Color Mapping ───────────────────────────────────────
  //
  // KML uses aabbggrr (alpha-blue-green-red) format.
  // These are derived from AppTheme.endangermentColors:
  //   not endangered: 0xFF4CAF50 → ff50af4c
  //   threatened:     0xFFFFC107 → ff07c1ff
  //   shifting:       0xFFFF9800 → ff0098ff
  //   moribund:       0xFFFF5722 → ff2257ff
  //   nearly extinct: 0xFFF44336 → ff3643f4
  //   extinct:        0xFF9E9E9E → ff9e9e9e

  static const Map<String, String> _endangermentKmlColors = {
    'not endangered': 'ff50af4c',
    'threatened': 'ff07c1ff',
    'shifting': 'ff0098ff',
    'moribund': 'ff2257ff',
    'nearly extinct': 'ff3643f4',
    'extinct': 'ff9e9e9e',
  };

  /// Human-readable labels for endangerment statuses.
  static const Map<String, String> _endangermentLabels = {
    'not endangered': 'Safe',
    'threatened': 'Threatened',
    'shifting': 'Shifting',
    'moribund': 'Moribund',
    'nearly extinct': 'Nearly Extinct',
    'extinct': 'Extinct',
  };

  // ─── Public API ─────────────────────────────────────────────────────────────

  /// Generate a complete KML document from a list of languages.
  ///
  /// The document includes:
  /// - Style definitions for each endangerment level
  /// - Placemarks organized into folders by endangerment status
  /// - LookAt elements for each placemark
  ///
  /// Only languages with valid coordinates are included.
  /// The [title] parameter sets the KML document name.
  static String generateKml(
    List<Language> languages, {
    String title = 'Global Language Distribution Map',
    String? description,
  }) {
    // Filter to languages with valid coordinates
    final validLanguages =
        languages.where((lang) => lang.hasCoordinates).toList();

    // Group by endangerment status
    final grouped = <String, List<Language>>{};
    for (final lang in validLanguages) {
      grouped.putIfAbsent(lang.endangeredStatus, () => []).add(lang);
    }

    // Build the KML document
    final builder = XmlBuilder();
    builder.processing('xml', 'version="1.0" encoding="UTF-8"');
    builder.element('kml',
        namespaces: {_kmlNamespace: ''},
        namespace: _kmlNamespace, nest: () {
      builder.element('Document', nest: () {
        // Document metadata
        builder.element('name', nest: title);
        builder.element('description', nest: () {
          builder.text(description ??
              '${validLanguages.length} languages from Glottolog & UNESCO datasets. '
                  'Generated by Global Language Distribution Map.');
        });
        builder.element('open', nest: '1');

        // Generate styles for each endangerment level
        _buildStyles(builder);

        // Generate folders grouped by endangerment status
        // Order: not endangered first, extinct last
        final statusOrder = [
          'not endangered',
          'threatened',
          'shifting',
          'moribund',
          'nearly extinct',
          'extinct',
        ];

        for (final status in statusOrder) {
          final langs = grouped[status];
          if (langs == null || langs.isEmpty) continue;
          _buildFolder(builder, status, langs);
        }

        // Include any languages with unexpected status values
        final knownStatuses = statusOrder.toSet();
        for (final entry in grouped.entries) {
          if (!knownStatuses.contains(entry.key)) {
            _buildFolder(builder, entry.key, entry.value);
          }
        }
      });
    });

    return builder.buildDocument().toXmlString(pretty: true, indent: '  ');
  }

  /// Generate a standalone KML document with a single language.
  ///
  /// Useful for sending a single placemark to Liquid Galaxy.
  static String generateSingleLanguageKml(Language language) {
    final builder = XmlBuilder();
    builder.processing('xml', 'version="1.0" encoding="UTF-8"');
    builder.element('kml',
        namespaces: {_kmlNamespace: ''},
        namespace: _kmlNamespace, nest: () {
      builder.element('Document', nest: () {
        builder.element('name', nest: language.name);
        _buildStyles(builder);
        _buildPlacemark(builder, language);
      });
    });

    return builder.buildDocument().toXmlString(pretty: true, indent: '  ');
  }

  /// Generate a standalone `<LookAt>` KML element.
  ///
  /// This is designed for future Liquid Galaxy integration where
  /// the viewpoint needs to be synced independently of placemarks.
  ///
  /// [range] is the distance from the point in meters (default: 50,000m ≈ 50km).
  /// [tilt] is the angle from nadir in degrees (0 = straight down, 90 = horizon).
  /// [heading] is the compass direction in degrees (0 = north).
  static String generateLookAtKml({
    required double latitude,
    required double longitude,
    double altitude = 0,
    double range = 50000,
    double tilt = 45,
    double heading = 0,
  }) {
    final builder = XmlBuilder();
    builder.processing('xml', 'version="1.0" encoding="UTF-8"');
    builder.element('kml',
        namespaces: {_kmlNamespace: ''},
        namespace: _kmlNamespace, nest: () {
      _buildLookAt(
        builder,
        latitude: latitude,
        longitude: longitude,
        altitude: altitude,
        range: range,
        tilt: tilt,
        heading: heading,
      );
    });

    return builder.buildDocument().toXmlString(pretty: true, indent: '  ');
  }

  // ─── Private Builders ───────────────────────────────────────────────────────

  /// Build <Style> elements for all endangerment levels.
  static void _buildStyles(XmlBuilder builder) {
    for (final entry in _endangermentKmlColors.entries) {
      final styleId = _statusToStyleId(entry.key);
      builder.element('Style', attributes: {'id': styleId}, nest: () {
        builder.element('IconStyle', nest: () {
          builder.element('color', nest: entry.value);
          builder.element('scale', nest: '1.0');
          builder.element('Icon', nest: () {
            builder.element('href', nest: () {
              builder.text(
                  'http://maps.google.com/mapfiles/kml/shapes/shaded_dot.png');
            });
          });
        });
        builder.element('LabelStyle', nest: () {
          builder.element('color', nest: entry.value);
          builder.element('scale', nest: '0.8');
        });
        builder.element('BalloonStyle', nest: () {
          builder.element('text', nest: () {
            builder.cdata(
              '<h3>\$[name]</h3>\$[description]',
            );
          });
        });
      });
    }
  }

  /// Build a `<Folder>` containing placemarks for a given endangerment status.
  static void _buildFolder(
    XmlBuilder builder,
    String status,
    List<Language> languages,
  ) {
    final label = _endangermentLabels[status] ?? status;
    builder.element('Folder', nest: () {
      builder.element('name', nest: '$label (${languages.length})');
      builder.element('open', nest: '0');

      for (final lang in languages) {
        _buildPlacemark(builder, lang);
      }
    });
  }

  /// Build a single `<Placemark>` element for a language.
  static void _buildPlacemark(XmlBuilder builder, Language language) {
    final label = _endangermentLabels[language.endangeredStatus] ??
        language.endangeredStatus;
    final styleId = _statusToStyleId(language.endangeredStatus);

    builder.element('Placemark', nest: () {
      builder.element('name', nest: language.name);
      builder.element('description', nest: () {
        builder.cdata(
          '<b>Language Family:</b> ${_escapeHtml(language.languageFamily)}<br/>'
          '<b>Region:</b> ${_escapeHtml(language.countryRegion)}<br/>'
          '<b>Status:</b> $label<br/>'
          '<b>Coordinates:</b> ${language.latitude.toStringAsFixed(4)}, '
          '${language.longitude.toStringAsFixed(4)}<br/>'
          '${language.description.isNotEmpty ? '<br/><i>${_escapeHtml(language.description)}</i>' : ''}',
        );
      });
      builder.element('styleUrl', nest: '#$styleId');

      // Point coordinates (KML format: longitude,latitude,altitude)
      builder.element('Point', nest: () {
        builder.element('coordinates', nest: () {
          builder.text(
              '${language.longitude},${language.latitude},0');
        });
      });

      // LookAt for camera positioning
      _buildLookAt(
        builder,
        latitude: language.latitude,
        longitude: language.longitude,
      );
    });
  }

  /// Build a `<LookAt>` element.
  static void _buildLookAt(
    XmlBuilder builder, {
    required double latitude,
    required double longitude,
    double altitude = 0,
    double range = 50000,
    double tilt = 45,
    double heading = 0,
  }) {
    builder.element('LookAt', nest: () {
      builder.element('longitude', nest: longitude.toStringAsFixed(6));
      builder.element('latitude', nest: latitude.toStringAsFixed(6));
      builder.element('altitude', nest: altitude.toStringAsFixed(0));
      builder.element('range', nest: range.toStringAsFixed(0));
      builder.element('tilt', nest: tilt.toStringAsFixed(0));
      builder.element('heading', nest: heading.toStringAsFixed(0));
      builder.element('altitudeMode', nest: 'relativeToGround');
    });
  }

  // ─── Utilities ──────────────────────────────────────────────────────────────

  /// Convert an endangerment status string to a KML style ID.
  static String _statusToStyleId(String status) {
    return 'style-${status.replaceAll(' ', '-')}';
  }

  /// Escape HTML special characters for CDATA content.
  static String _escapeHtml(String text) {
    return text
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&#39;');
  }
}
